# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CESNET.
#
# Invenio OpenID Connect is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
  global:
    #- POSTGRESQL_SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
    - ES7_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-linux-x86_64.tar.gz"
    - ES_HOST=127.0.0.1
  matrix:
    - REQUIREMENTS=release OAREPO_VERSION=3.3.0 ES=$ES7_DOWNLOAD_URL EXTRAS=tests

python:
  - "3.8"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder pip-tools"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.in"
  - "pip-compile -U --verbose -o .travis-release-requirements.txt .travis-release-requirements.in"
  - cat .travis-release-requirements.txt
  - mkdir /tmp/elasticsearch
  - wget -O - $ES | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - sleep 10

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[$EXTRAS]"
  - "travis_retry pip install -e sample"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Cz+yLu4w3y8RJNBPM+dgIILQWJN35/oM1TbK5dyiXFzlO6mem82dXuOJ8Zz16PO0I93SPrZ44rKD7v43l69ULigBZTvLLqPgtVkKoPoN/yvpvDMoLKmF+ps5jpIge9R+SI5K6NkibXM5FKXlhUuZdirPfHKE9tCxB8HOz5JqFIRuu422yjDIZ7gOfxQUhoLkUYn0hLEDsznOclyjwQeW+6VaMfdr7Y0luGKJlF2QLlNqhw0iTzZgD85JVEhCkHQWNlwLKm/umK6zFku//fZQW5f2y+hTULkVKIOXGCC4DcR9C8tjep2D5FEvSyXCOPPBnjS97ED4EIJe1rjEe9lvxRF8CrIqPjv8XPDp2VSftakOTl1ZLkQ0K1SBCE3CvMqoNFL28HIyYHAedzdauC6Pb4uSO1n2lV266fOeF8876KEAC+4ZDYAAeyfzSr8x32Idoggn6V2qJiRfH4tcdsne1yDPuOCoMWVToQeQiryozBDErPmYTnf6FQUoX644y2on0WIfGK1GewtvBnVpu6eu/fnYLkiFX9hebZ+GzY3UMxviA56QYf4MfxuBHC1QjpwNPCBvOLgBV573F2Z96PvJSZ05BNYYDs4tUfltSdj7aJUe5tcfk7hlpmLEvhz3FVJtik9oGZC8RE149J66/2x761qii7+xRl5aBIXQxjiDP3U="
  on:
    tags: true
    branch: master
  distributions: "sdist bdist_wheel"
  skip_existing: true
